Fix: Deployment3

diff --git a/.github/workflows/deploy-to-s3.yml b/.github/workflows/deploy-to-s3.yml
--- a/.github/workflows/deploy-to-s3.yml
+++ b/.github/workflows/deploy-to-s3.yml
@@ -18,9 +18,17 @@ jobs:
 
       - name: Set up AWS CLI
         run: |
-          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
+          # Check if AWS CLI v2 is already installed, and if not, install it
+          if ! command -v aws &> /dev/null
+          then
+            echo "AWS CLI not found, installing..."
+            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          else
+            echo "AWS CLI is already installed, updating..."
+            sudo /usr/local/aws-cli/v2/current/bin/aws --update
+          fi
 
       - name: Configure AWS CLI
         run: |
@@ -31,4 +39,3 @@ jobs:
       - name: Sync files to S3
         run: |
           aws s3 sync . s3://${{ secrets.S3_BUCKET }} --delete --no-acl
-
